version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8002:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: youtube_laravel
      MYSQL_DATABASE: youtube_laravel
      MYSQL_USER: youtube_laravel
      MYSQL_PASSWORD: youtube_laravel
    volumes:
      - ./docker/mysql/example.sql:/docker-entrypoint-initdb.d/example.sql
    ports:
      - "3301:3306"

  node:
    container_name: node
    image: node:18
    working_dir: /var/www/client
    volumes:
      - ./client:/var/www/client
    ports:
      - "3002:3000"
    stdin_open: true
    tty: true